### ISSUE TITLE
Dubious line of code

### ISSUE THREAD

**Issue by norswap** [asanso/Bandersnatch#4]
https://github.com/asanso/Bandersnatch/blob/bfeb61c903a3e00021e1d38c569d89a2e704cd27/python-ref-impl/curve.py#L139

Shouldn't this be `P = self.neg()`?

But then `P = self` should be added at the top and this line modified too:

https://github.com/asanso/Bandersnatch/blob/bfeb61c903a3e00021e1d38c569d89a2e704cd27/python-ref-impl/curve.py#L143

**Comment by simonmasson** [comment]
Thank you for this remark. I added it in the commit `f6c6090e9a5da4bb0bc03a334832e85d36da260d`. I also added a test in `test.py`.
